name: "CloudFlare DNSLink"
description: "Creates and updates  CloudFlare DNSLink"
author: "Xuemomo"

inputs:
  domain:
    description: 'domin'
    required: true
  cid:
    description: 'Ipfs cid'
    required: true
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    default: "CloudFlare zone"
    required: true
outputs:
  record_id:
    description: "Record ID"
  name:
    description: 'Affected domain name'
runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "cloud"
  color: "orange"
